// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package datastore represents the imported interface "wasmvision:platform/datastore".
package datastore

import (
	"go.bytecodealliance.org/cm"
)

// DatastoreError represents the enum "wasmvision:platform/datastore#datastore-error".
//
// datastore errors returned by the runtime.
//
//	enum datastore-error {
//		success,
//		no-such-frame,
//		no-such-key,
//		runtime-error
//	}
type DatastoreError uint8

const (
	DatastoreErrorSuccess DatastoreError = iota
	DatastoreErrorNoSuchFrame
	DatastoreErrorNoSuchKey
	DatastoreErrorRuntimeError
)

var _DatastoreErrorStrings = [4]string{
	"success",
	"no-such-frame",
	"no-such-key",
	"runtime-error",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e DatastoreError) String() string {
	return _DatastoreErrorStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e DatastoreError) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *DatastoreError) UnmarshalText(text []byte) error {
	return _DatastoreErrorUnmarshalCase(e, text)
}

var _DatastoreErrorUnmarshalCase = cm.CaseUnmarshaler[DatastoreError](_DatastoreErrorStrings[:])

// FrameStore represents the imported resource "wasmvision:platform/datastore#frame-store".
//
// frame-store is the interface for storing data associated with a specific frame.
//
//	resource frame-store
type FrameStore cm.Resource

// ResourceDrop represents the imported resource-drop for resource "frame-store".
//
// Drops a resource handle.
//
//go:nosplit
func (self FrameStore) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_FrameStoreResourceDrop((uint32)(self0))
	return
}

// NewFrameStore represents the imported constructor for resource "frame-store".
//
// The id param is currently ignored
//
//	constructor(id: u32)
//
//go:nosplit
func NewFrameStore(id uint32) (result FrameStore) {
	id0 := (uint32)(id)
	result0 := wasmimport_NewFrameStore((uint32)(id0))
	result = cm.Reinterpret[FrameStore]((uint32)(result0))
	return
}

// Delete represents the imported method "delete".
//
// Delete the data with the specified `key` for the specified `frame`
//
// No error is raised if a tuple did not previously exist for `key`.
//
//	delete: func(frame: u32, key: string) -> result<_, datastore-error>
//
//go:nosplit
func (self FrameStore) Delete(frame uint32, key string) (result cm.Result[DatastoreError, struct{}, DatastoreError]) {
	self0 := cm.Reinterpret[uint32](self)
	frame0 := (uint32)(frame)
	key0, key1 := cm.LowerString(key)
	wasmimport_FrameStoreDelete((uint32)(self0), (uint32)(frame0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// DeleteAll represents the imported method "delete-all".
//
// Delete all data for the specified `frame`.
//
// No error is raised if no data exists for the `frame`.
//
//	delete-all: func(frame: u32) -> result<_, datastore-error>
//
//go:nosplit
func (self FrameStore) DeleteAll(frame uint32) (result cm.Result[DatastoreError, struct{}, DatastoreError]) {
	self0 := cm.Reinterpret[uint32](self)
	frame0 := (uint32)(frame)
	wasmimport_FrameStoreDeleteAll((uint32)(self0), (uint32)(frame0), &result)
	return
}

// Exists represents the imported method "exists".
//
// Return whether data exists for the specified `frame`
//
//	exists: func(frame: u32) -> result<bool, datastore-error>
//
//go:nosplit
func (self FrameStore) Exists(frame uint32) (result cm.Result[DatastoreError, bool, DatastoreError]) {
	self0 := cm.Reinterpret[uint32](self)
	frame0 := (uint32)(frame)
	wasmimport_FrameStoreExists((uint32)(self0), (uint32)(frame0), &result)
	return
}

// Get represents the imported method "get".
//
// Get the value associated with the specified `key` for the specific frame.
//
// Returns `ok(none)` if the key does not exist.
//
//	get: func(frame: u32, key: string) -> result<string, datastore-error>
//
//go:nosplit
func (self FrameStore) Get(frame uint32, key string) (result cm.Result[string, string, DatastoreError]) {
	self0 := cm.Reinterpret[uint32](self)
	frame0 := (uint32)(frame)
	key0, key1 := cm.LowerString(key)
	wasmimport_FrameStoreGet((uint32)(self0), (uint32)(frame0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// GetKeys represents the imported method "get-keys".
//
// Return a list of all the keys. returns empty list if no keys are present.
//
//	get-keys: func(frame: u32) -> list<string>
//
//go:nosplit
func (self FrameStore) GetKeys(frame uint32) (result cm.List[string]) {
	self0 := cm.Reinterpret[uint32](self)
	frame0 := (uint32)(frame)
	wasmimport_FrameStoreGetKeys((uint32)(self0), (uint32)(frame0), &result)
	return
}

// Set represents the imported method "set".
//
// Set the `value` associated with the specified `key` for the specific frame
// overwriting any existing value.
//
//	set: func(frame: u32, key: string, value: string) -> result<_, datastore-error>
//
//go:nosplit
func (self FrameStore) Set(frame uint32, key string, value string) (result cm.Result[DatastoreError, struct{}, DatastoreError]) {
	self0 := cm.Reinterpret[uint32](self)
	frame0 := (uint32)(frame)
	key0, key1 := cm.LowerString(key)
	value0, value1 := cm.LowerString(value)
	wasmimport_FrameStoreSet((uint32)(self0), (uint32)(frame0), (*uint8)(key0), (uint32)(key1), (*uint8)(value0), (uint32)(value1), &result)
	return
}

// ProcessorStore represents the imported resource "wasmvision:platform/datastore#processor-store".
//
// processor-store is the interface for storing data associated with a processor.
//
//	resource processor-store
type ProcessorStore cm.Resource

// ResourceDrop represents the imported resource-drop for resource "processor-store".
//
// Drops a resource handle.
//
//go:nosplit
func (self ProcessorStore) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ProcessorStoreResourceDrop((uint32)(self0))
	return
}

// NewProcessorStore represents the imported constructor for resource "processor-store".
//
// The id param is currently ignored
//
//	constructor(id: u32)
//
//go:nosplit
func NewProcessorStore(id uint32) (result ProcessorStore) {
	id0 := (uint32)(id)
	result0 := wasmimport_NewProcessorStore((uint32)(id0))
	result = cm.Reinterpret[ProcessorStore]((uint32)(result0))
	return
}

// Delete represents the imported method "delete".
//
// Delete the tuple with the specified `key`
//
// No error is raised if a tuple did not previously exist for `key`.
//
//	delete: func(processor: string, key: string) -> result<_, datastore-error>
//
//go:nosplit
func (self ProcessorStore) Delete(processor string, key string) (result cm.Result[DatastoreError, struct{}, DatastoreError]) {
	self0 := cm.Reinterpret[uint32](self)
	processor0, processor1 := cm.LowerString(processor)
	key0, key1 := cm.LowerString(key)
	wasmimport_ProcessorStoreDelete((uint32)(self0), (*uint8)(processor0), (uint32)(processor1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// DeleteAll represents the imported method "delete-all".
//
// Delete all the data for the specified `processor`.
//
// No error is raised if no data exists for the `processor`.
//
//	delete-all: func(processor: string) -> result<_, datastore-error>
//
//go:nosplit
func (self ProcessorStore) DeleteAll(processor string) (result cm.Result[DatastoreError, struct{}, DatastoreError]) {
	self0 := cm.Reinterpret[uint32](self)
	processor0, processor1 := cm.LowerString(processor)
	wasmimport_ProcessorStoreDeleteAll((uint32)(self0), (*uint8)(processor0), (uint32)(processor1), &result)
	return
}

// Exists represents the imported method "exists".
//
// Return whether data exists for the specified `processor`.
//
//	exists: func(processor: string) -> result<bool, datastore-error>
//
//go:nosplit
func (self ProcessorStore) Exists(processor string) (result cm.Result[DatastoreError, bool, DatastoreError]) {
	self0 := cm.Reinterpret[uint32](self)
	processor0, processor1 := cm.LowerString(processor)
	wasmimport_ProcessorStoreExists((uint32)(self0), (*uint8)(processor0), (uint32)(processor1), &result)
	return
}

// Get represents the imported method "get".
//
// Get the value associated with the specified `key`
//
// Returns `ok(none)` if the key does not exist.
//
//	get: func(processor: string, key: string) -> result<string, datastore-error>
//
//go:nosplit
func (self ProcessorStore) Get(processor string, key string) (result cm.Result[string, string, DatastoreError]) {
	self0 := cm.Reinterpret[uint32](self)
	processor0, processor1 := cm.LowerString(processor)
	key0, key1 := cm.LowerString(key)
	wasmimport_ProcessorStoreGet((uint32)(self0), (*uint8)(processor0), (uint32)(processor1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// GetKeys represents the imported method "get-keys".
//
// Return a list of all the keys. returns empty list if no keys are present.
//
//	get-keys: func(processor: string) -> list<string>
//
//go:nosplit
func (self ProcessorStore) GetKeys(processor string) (result cm.List[string]) {
	self0 := cm.Reinterpret[uint32](self)
	processor0, processor1 := cm.LowerString(processor)
	wasmimport_ProcessorStoreGetKeys((uint32)(self0), (*uint8)(processor0), (uint32)(processor1), &result)
	return
}

// Set represents the imported method "set".
//
// Set the `value` associated with the specified `key` overwriting any existing value.
//
//	set: func(processor: string, key: string, value: string) -> result<_, datastore-error>
//
//go:nosplit
func (self ProcessorStore) Set(processor string, key string, value string) (result cm.Result[DatastoreError, struct{}, DatastoreError]) {
	self0 := cm.Reinterpret[uint32](self)
	processor0, processor1 := cm.LowerString(processor)
	key0, key1 := cm.LowerString(key)
	value0, value1 := cm.LowerString(value)
	wasmimport_ProcessorStoreSet((uint32)(self0), (*uint8)(processor0), (uint32)(processor1), (*uint8)(key0), (uint32)(key1), (*uint8)(value0), (uint32)(value1), &result)
	return
}
