// Code generated by wit-bindgen-go. DO NOT EDIT.

package datastore

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasmvision:platform".

//go:wasmimport wasmvision:platform/datastore [resource-drop]frame-store
//go:noescape
func wasmimport_FrameStoreResourceDrop(self0 uint32)

//go:wasmimport wasmvision:platform/datastore [constructor]frame-store
//go:noescape
func wasmimport_NewFrameStore(id0 uint32) (result0 uint32)

//go:wasmimport wasmvision:platform/datastore [method]frame-store.delete
//go:noescape
func wasmimport_FrameStoreDelete(self0 uint32, frame0 uint32, key0 *uint8, key1 uint32, result *cm.Result[DatastoreError, bool, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]frame-store.exists
//go:noescape
func wasmimport_FrameStoreExists(self0 uint32, frame0 uint32, key0 *uint8, key1 uint32, result *cm.Result[DatastoreError, bool, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]frame-store.get
//go:noescape
func wasmimport_FrameStoreGet(self0 uint32, frame0 uint32, key0 *uint8, key1 uint32, result *cm.Result[cm.List[uint8], cm.List[uint8], DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]frame-store.get-keys
//go:noescape
func wasmimport_FrameStoreGetKeys(self0 uint32, frame0 uint32, result *cm.Result[cm.List[string], cm.List[string], DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]frame-store.set
//go:noescape
func wasmimport_FrameStoreSet(self0 uint32, frame0 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[DatastoreError, bool, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [resource-drop]processor-store
//go:noescape
func wasmimport_ProcessorStoreResourceDrop(self0 uint32)

//go:wasmimport wasmvision:platform/datastore [constructor]processor-store
//go:noescape
func wasmimport_NewProcessorStore(id0 uint32) (result0 uint32)

//go:wasmimport wasmvision:platform/datastore [method]processor-store.delete
//go:noescape
func wasmimport_ProcessorStoreDelete(self0 uint32, processor0 *uint8, processor1 uint32, key0 *uint8, key1 uint32, result *cm.Result[DatastoreError, bool, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]processor-store.exists
//go:noescape
func wasmimport_ProcessorStoreExists(self0 uint32, processor0 *uint8, processor1 uint32, key0 *uint8, key1 uint32, result *cm.Result[DatastoreError, bool, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]processor-store.get
//go:noescape
func wasmimport_ProcessorStoreGet(self0 uint32, processor0 *uint8, processor1 uint32, key0 *uint8, key1 uint32, result *cm.Result[cm.List[uint8], cm.List[uint8], DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]processor-store.get-keys
//go:noescape
func wasmimport_ProcessorStoreGetKeys(self0 uint32, processor0 *uint8, processor1 uint32, result *cm.Result[cm.List[string], cm.List[string], DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]processor-store.set
//go:noescape
func wasmimport_ProcessorStoreSet(self0 uint32, processor0 *uint8, processor1 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[DatastoreError, bool, DatastoreError])
