// Code generated by wit-bindgen-go. DO NOT EDIT.

package datastore

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasmvision:platform".

//go:wasmimport wasmvision:platform/datastore [resource-drop]framedata
//go:noescape
func wasmimport_FramedataResourceDrop(self0 uint32)

//go:wasmimport wasmvision:platform/datastore [static]framedata.open
//go:noescape
func wasmimport_FramedataOpen(frame0 uint32, result *cm.Result[Framedata, Framedata, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]framedata.delete
//go:noescape
func wasmimport_FramedataDelete(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[DatastoreError, struct{}, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]framedata.exists
//go:noescape
func wasmimport_FramedataExists(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[bool, bool, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]framedata.get
//go:noescape
func wasmimport_FramedataGet(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[cm.List[uint8], cm.List[uint8], DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]framedata.get-keys
//go:noescape
func wasmimport_FramedataGetKeys(self0 uint32, result *cm.Result[cm.List[string], cm.List[string], DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]framedata.set
//go:noescape
func wasmimport_FramedataSet(self0 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[DatastoreError, struct{}, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [resource-drop]processordata
//go:noescape
func wasmimport_ProcessordataResourceDrop(self0 uint32)

//go:wasmimport wasmvision:platform/datastore [static]processordata.open
//go:noescape
func wasmimport_ProcessordataOpen(processor0 *uint8, processor1 uint32, result *cm.Result[Processordata, Processordata, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]processordata.delete
//go:noescape
func wasmimport_ProcessordataDelete(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[DatastoreError, struct{}, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]processordata.exists
//go:noescape
func wasmimport_ProcessordataExists(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[bool, bool, DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]processordata.get
//go:noescape
func wasmimport_ProcessordataGet(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[cm.List[uint8], cm.List[uint8], DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]processordata.get-keys
//go:noescape
func wasmimport_ProcessordataGetKeys(self0 uint32, result *cm.Result[cm.List[string], cm.List[string], DatastoreError])

//go:wasmimport wasmvision:platform/datastore [method]processordata.set
//go:noescape
func wasmimport_ProcessordataSet(self0 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[DatastoreError, struct{}, DatastoreError])
