// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package logging represents the imported interface "wasmvision:platform/logging".
package logging

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
)

// Log represents the imported function "log".
//
// Log a message on the host.
//
//	log: func(msg: string)
//
//go:nosplit
func Log(msg string) {
	msg0, msg1 := cm.LowerString(msg)
	wasmimport_Log((*uint8)(msg0), (uint32)(msg1))
	return
}

// Println represents the imported function "println".
//
// Print a message on the host.
//
//	println: func(msg: string)
//
//go:nosplit
func Println(msg string) {
	msg0, msg1 := cm.LowerString(msg)
	wasmimport_Println((*uint8)(msg0), (uint32)(msg1))
	return
}
