// Code generated by wit-bindgen-go. DO NOT EDIT.

package logging

// This file contains wasmimport and wasmexport declarations for "wasmvision:platform".

//go:wasmimport wasmvision:platform/logging log
//go:noescape
func wasmimport_Log(msg0 *uint8, msg1 uint32)

//go:wasmimport wasmvision:platform/logging println
//go:noescape
func wasmimport_Println(msg0 *uint8, msg1 uint32)
