// Code generated by wit-bindgen-go. DO NOT EDIT.

package config

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasmvision:platform".

//go:wasmimport wasmvision:platform/config get-config
//go:noescape
func wasmimport_GetConfig(key0 *uint8, key1 uint32, result *cm.Result[string, string, ConfigError])
