// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package time represents the imported interface "wasmvision:platform/time".
package time

// Now represents the imported function "now".
//
// Get the current time in milliseconds since the Unix epoch.
//
//	now: func() -> u64
//
//go:nosplit
func Now() (result uint64) {
	result0 := wasmimport_Now()
	result = (uint64)((uint64)(result0))
	return
}
