// Code generated by wit-bindgen-go. DO NOT EDIT.

package time

// This file contains wasmimport and wasmexport declarations for "wasmvision:platform".

//go:wasmimport wasmvision:platform/time now
//go:noescape
func wasmimport_Now() (result0 uint64)
