// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package time represents the imported interface "wasmvision:platform/time".
package time

// Now represents the imported function "now".
//
// Get the current time in milliseconds since the Unix epoch. Use 0 for the `tz` parameter
// for now.
//
//	now: func(tz: u32) -> u64
//
//go:nosplit
func Now(tz uint32) (result uint64) {
	tz0 := (uint32)(tz)
	result0 := wasmimport_Now((uint32)(tz0))
	result = (uint64)((uint64)(result0))
	return
}
