// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package imports represents the world "wasmvision:platform/imports".
//
// wasmvision is a WebAssembly guest module interface for host functions provided
// by the wasmVision runtime.
package imports
